defaults:
  - train_iqa_finetune
  - _self_

job:
  run_name: iqa_finetune_uma_3term

starting_checkpoint: "/checkpoint/ocp/shared/uma/202505-0117-1812-5a58/checkpoints/final/inference_ckpt.pt" # Update to your custom checkpoint output logic
