data_root_dir: /data/horse/ws/maho053h-iqa-training/HCNOSPClF_combined_datasets_filtered0.001
run_dir: /data/horse/ws/maho053h-iqa-training/iqa

#run_dir: ${oc.env:PWD}/runs
account: null
qos: null
mode: SLURM
device: CUDA
ranks_per_node: 8
dataloader_workers: 8
debug: False
mem_gb: 0
cpus_per_task: 6
timeout_hr: "168"
partition: alpha
