data_root_dir: /home/lukas/uni/whk/HCNOSPClF_combined_datasets_filtered0.001
run_dir: /home/lukas/uni/whk/runs
#run_dir: ${oc.env:PWD}/runs
account: null
qos: null
mode: LOCAL
device: CUDA
ranks_per_node: 1
dataloader_workers: 1
debug: False
mem_gb: 0
cpus_per_task: 4
timeout_hr: "48"
partition: paula
max_atoms: 10  # Reduced for local testing to avoid OOM

