- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: iqa_intra_a
  level: atom
  property: node_pred
  datasets: ${dataset_list}
  element_references:
    _target_: fairchem.core.modules.normalization.element_references.AtomElementReferences
    element_references:
      _target_: torch.DoubleTensor
      _args_:
        - ${element_refs.iqa_intra_elem_refs}
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.MAELoss
    coefficient: ${iqa_intra_a_coef}
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: ${normalizer_mean_iqa_intra_a}
    rmsd: ${normalizer_rmsd_iqa_intra_a}
  out_spec:
    dim: [1]
    dtype: float32
    iqa_components_head:
      prediction_key: node_pred
      label_key: iqa_intra_a

- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: iqa_inter_a
  level: atom
  property: node_pred
  datasets: ${dataset_list}
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.MAELoss
    coefficient: ${iqa_inter_a_coef}
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: ${normalizer_mean_iqa_inter_a}
    rmsd: ${normalizer_rmsd_iqa_inter_a}
  out_spec:
    dim: [1]
    dtype: float32
    iqa_components_head:
      prediction_key: node_pred
      label_key: iqa_inter_a

- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: iqa_inter_ab
  level: edge
  property: edge_pred
  datasets: ${dataset_list}
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.MAELoss
    coefficient: ${iqa_inter_ab_coef}
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: ${normalizer_mean_iqa_inter_ab}
    rmsd: ${normalizer_rmsd_iqa_inter_ab}
  out_spec:
    dim: [1]
    dtype: float32
    iqa_components_head:
      prediction_key: edge_pred
      label_key: iqa_inter_ab

- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: iqa_forces_direct
  level: atom
  property: forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.L2NormLoss
    reduction: ${force_loss_reduction}
    coefficient: ${force_direct_coef}
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: ${normalizer_mean_iqa_force}
    rmsd: ${normalizer_rmsd_iqa_force}
  out_spec:
    dim: [3]
    dtype: float32
  datasets: ${dataset_list}
  metrics: []

- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: iqa_forces_grad
  level: atom
  property: forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  loss_fn:
    _target_: fairchem.core.modules.loss.DDPMTLoss
    loss_fn:
      _target_: fairchem.core.modules.loss.L2NormLoss
    reduction: ${force_loss_reduction}
    coefficient: ${force_grad_coef}
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: ${normalizer_mean_iqa_force}
    rmsd: ${normalizer_rmsd_iqa_force}
  out_spec:
    dim: [3]
    dtype: float32
  datasets: ${dataset_list}
  metrics: []
