iqa_train:
  _target_: fairchem.core.datasets.iqa_pkl_dataset.IQAPKLDataset
  src: ${cluster.data_root_dir}/train
  name: iqa_pkl
  enforce_consistent_keys: true
  ht2ev: true
  key_mapping:
    energy: e_total
    iqa_kinetic: T(A)
    iqa_vne: Vne(A,A)
    iqa_vee: Vee(A,A)
    iqa_inter: E_IQA_Inter(A)
    # Edge-level pairwise IQA components
    iqa_inter_edge: E_IQA_Inter(A,B)/2
    iqa_vee_edge: Vee(A,B)/2
    iqa_vne_edge: Vne(A,B)/2
    iqa_ven_edge: Ven(A,B)/2
    iqa_vnn_edge: Vnn(A,B)/2

iqa_val:
  _target_: fairchem.core.datasets.iqa_pkl_dataset.IQAPKLDataset
  src: ${cluster.data_root_dir}/val
  name: iqa_pkl
  enforce_consistent_keys: true
  ht2ev: true
  key_mapping:
    energy: e_total
    iqa_kinetic: T(A)
    iqa_vne: Vne(A,A)
    iqa_vee: Vee(A,A)
    iqa_inter: E_IQA_Inter(A)
    # Edge-level pairwise IQA components
    iqa_inter_edge: E_IQA_Inter(A,B)/2
    iqa_vee_edge: Vee(A,B)/2
    iqa_vne_edge: Vne(A,B)/2
    iqa_ven_edge: Ven(A,B)/2
    iqa_vnn_edge: Vnn(A,B)/2
